kotlin.code.style=official

# Plugin versions
kotlinVersion=2.4.10
kotlinterVersion=5.7.0

# Dependency versions
hagDomeneInntektsmeldingVersion=0.11.2
junitJupiterVersion=6.1.3
kotestVersion=6.2.4
kotlinxCoroutinesVersion=1.11.0
kotlinxSerializationVersion=1.11.0
ktorVersion=3.5.2
mockkVersion=1.14.11
utilsVersion=0.10.2
