kafkaPool: nav-dev
azure:
  enabled: true
ingress: https://helsearbeidsgiver-im-notifikasjon.dev.nav.no
env:
  - name: ARBEIDSGIVER_NOTIFIKASJON_API_URL
    value: "https://ag-notifikasjon-produsent-api.dev.nav.no/api/graphql"
  - name: ARBEIDSGIVER_NOTIFIKASJON_SCOPE
    value: "api://dev-gcp.fager.notifikasjon-produsent-api/.default"
  - name: LINK_URL
    value: "https://arbeidsgiver.dev.nav.no"
