kafkaPool: nav-dev
azure:
  enabled: true
database:
  - name: notifikasjon
logical_decoding: true
dbTier: db-custom-1-3840
envFrom:
  - type: secret
    name: google-sql-im-notifikasjon
secureLogs:
  enabled: true
env:
  - name: ARBEIDSGIVER_NOTIFIKASJON_API_URL
    value: "http://notifikasjon-produsent-api.fager/api/graphql"
  - name: ARBEIDSGIVER_NOTIFIKASJON_SCOPE
    value: "api://dev-gcp.fager.notifikasjon-produsent-api/.default"
  - name: LINK_URL
    value: "https://arbeidsgiver.intern.dev.nav.no"
  - name: REDIS_URL
    value: redis://helsearbeidsgiver-redis.helsearbeidsgiver.svc.cluster.local:6379/0
  - name: OPPGAVEPAAMINNELSER_AKTIVERT
    value: "true"
  - name: TID_MELLOM_OPPGAVEOPPRETTELSE_OG_PAAMINNELSE
    value: "P3M"
apps:
  - name: helsearbeidsgiver-redis
  - name: notifikasjon-produsent-api
    namespace: fager
