kafkaPool: nav-dev
azure:
  enabled: true
ingress: https://helsearbeidsgiver-im-notifikasjon.dev.nav.no
env:
- name: NOTIFIKASJON_URL
  value: "https://ag-notifikasjon-produsent-api.dev.nav.no/"
- name: LINK_URL
  value: "https://arbeidsgiver.dev.nav.no"
- name: PROXY_SCOPE
  value: "api://dev-fss.helsearbeidsgiver.helsearbeidsgiver-proxy/.default"
