kafkaPool: nav-prod
azure:
  enabled: true
secureLogs:
  enabled: true
env:
  - name: ARBEIDSGIVER_NOTIFIKASJON_API_URL
    value: "http://notifikasjon-produsent-api.fager/api/graphql"
  - name: ARBEIDSGIVER_NOTIFIKASJON_SCOPE
    value: "api://prod-gcp.fager.notifikasjon-produsent-api/.default"
  - name: LINK_URL
    value: "https://arbeidsgiver.nav.no"
apps:
  - name: notifikasjon-produsent-api
    namespace: fager
