kafkaPool: nav-prod
azure:
  enabled: true
database:
  - name: notifikasjon
    tier: db-custom-1-3840
logical_decoding: true
envFrom:
  - type: secret
    name: google-sql-im-notifikasjon
secureLogs:
  enabled: true
env:
  - name: ARBEIDSGIVER_NOTIFIKASJON_API_URL
    value: "http://notifikasjon-produsent-api.fager/api/graphql"
  - name: ARBEIDSGIVER_NOTIFIKASJON_SCOPE
    value: "api://prod-gcp.fager.notifikasjon-produsent-api/.default"
  - name: LINK_URL
    value: "https://arbeidsgiver.nav.no"
  - name: REDIS_URL
    value: redis://helsearbeidsgiver-redis.helsearbeidsgiver.svc.cluster.local:6379/0
apps:
  - name: helsearbeidsgiver-redis
  - name: notifikasjon-produsent-api
    namespace: fager
