kafkaPool: nav-prod
azure:
  enabled: true
secureLogs:
  enabled: true
env:
  - name: ARBEIDSGIVER_NOTIFIKASJON_API_URL
    value: "https://ag-notifikasjon-produsent-api.intern.nav.no/api/graphql"
  - name: ARBEIDSGIVER_NOTIFIKASJON_SCOPE
    value: "api://prod-gcp.fager.notifikasjon-produsent-api/.default"
  - name: LINK_URL
    value: "https://arbeidsgiver.nav.no"
  - name: REDIS_URL
    value: redis://helsearbeidsgiver-redis.helsearbeidsgiver.svc.cluster.local:6379/0
apps:
  - name: helsearbeidsgiver-redis
  - name: notifikasjon-produsent-api
    namespace: fager
externalHosts:
  - ag-notifikasjon-produsent-api.intern.nav.no
