openapi: 3.0.3
servers:
  - url: /v3
info:
  description: |-
    Inntektdokument
  version: 0.0.1
  title: Intektdokument spesifikasjon - OpenAPI 3.0
  termsOfService: 'http://swagger.io/terms/'
paths: {}
components:
  schemas:
    KvitteringResponse:
      type: object
      required:
        - orgnrUnderenhet
        - identitetsnummer
        - fulltNavn
        - virksomhetNavn
        - behandlingsdager
        - egenmeldingsperioder
        - arbeidsgiverperioder
        - bestemmendeFraværsdag
        - fraværsperioder
        - inntekt
        - refusjon
        - årsakInnsending
        - bekreftOpplysninger
        - tidspunkt
      properties:
        orgnrUnderenhet:
          type: string
        identitetsnummer:
          type: string
        fulltNavn:
          type: string
        telefonnummer:
          type: string
        innsenderNavn:
          type: string
        virksomhetNavn:
          type: string
        behandlingsdager:
          type: array
          items:
            type: string
            format: date
        egenmeldingsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
        arbeidsgiverperioder:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
        bestemmendeFraværsdag:
          type: string
          format: date
        fraværsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
        inntekt:
          $ref: '#/components/schemas/Inntekt'
        fullLønnIArbeidsgiverPerioden:
          $ref: '#/components/schemas/FullLonnIArbeidsgiverPerioden'
        refusjon:
          $ref: '#/components/schemas/Refusjon'
        naturalytelser:
          type: array
          items:
            $ref: '#/components/schemas/Naturalytelse'
        årsakInnsending:
          $ref: '#/components/schemas/ÅrsakInnsending'
        bekreftOpplysninger:
          type: boolean
        tidspunkt:
          type: string
          format: date-time
          pattern: yyyy-MM-dd'T'HH:mm:ss.SSSxx
        forespurtData:
          type: array
          items:
            type: string
    InnsendingRequest:
      type: object
      required:
        - orgnrUnderenhet
        - identitetsnummer
        - behandlingsdager
        - egenmeldingsperioder
        - arbeidsgiverperioder
        - bestemmendeFraværsdag
        - fraværsperioder
        - inntekt
        - refusjon
        - årsakInnsending
        - bekreftOpplysninger
      properties:
        orgnrUnderenhet:
          type: string
        identitetsnummer:
          type: string
        behandlingsdager:
          type: array
          items:
            type: string
            format: date
        egenmeldingsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
        arbeidsgiverperioder:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
        bestemmendeFraværsdag:
          type: string
          format: date
        fraværsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
        inntekt:
          $ref: '#/components/schemas/Inntekt'
        fullLønnIArbeidsgiverPerioden:
          $ref: '#/components/schemas/FullLonnIArbeidsgiverPerioden'
        refusjon:
          $ref: '#/components/schemas/Refusjon'
        naturalytelser:
          type: array
          items:
            $ref: '#/components/schemas/Naturalytelse'
        årsakInnsending:
          $ref: '#/components/schemas/ÅrsakInnsending'
        bekreftOpplysninger:
          type: boolean
        telefonnummer:
          type: string
        forespurtData:
          type: array
          items:
            type: string
    Inntekt:
      type: object
      required:
        - bekreftet
        - beregnetInntekt
        - manueltKorrigert
      properties:
        bekreftet:
          type: boolean
        beregnetInntekt:
          type: number
        endringÅrsak:
          $ref: '#/components/schemas/InntektEndringAarsak'
        manueltKorrigert:
          type: boolean

    InntektEndringAarsak:
      type: object
      required:
        - typpe
      discriminator:
        propertyName: typpe
      properties:
        typpe:
          type: string
    Nyansatt:
      allOf:
        - $ref: '#/components/schemas/InntektEndringAarsak'
    Tariffendring:
      required:
        - gjelderFra
        - bleKjent
      allOf:
        - $ref: '#/components/schemas/InntektEndringAarsak'
      properties:
        gjelderFra:
          type: string
          format: date
        bleKjent:
          type: string
          format: date
    Sykefravaer:
      required:
        - liste
      allOf:
        - $ref: '#/components/schemas/InntektEndringAarsak'
      properties:
        liste:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
    Ferie:
      required:
        - liste
      allOf:
        - $ref: '#/components/schemas/InntektEndringAarsak'
      properties:
        liste:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
    VarigLonnsendring:
      required:
        - gjelderFra
      allOf:
        - $ref: '#/components/schemas/InntektEndringAarsak'
      properties:
        gjelderFra:
          type: string
          format: date
    NyStilling:
      required:
        - gjelderFra
      allOf:
        - $ref: '#/components/schemas/InntektEndringAarsak'
      properties:
        gjelderFra:
          type: string
          format: date
    NyStillingsprosent:
      required:
        - gjelderFra
      allOf:
        - $ref: '#/components/schemas/InntektEndringAarsak'
      properties:
        gjelderFra:
          type: string
          format: date
    Bonus:
      allOf:
        - $ref: '#/components/schemas/InntektEndringAarsak'
      properties:
        aarligBonus:
          type: number
        datoForBonus:
          type: string
          format: date
    Permisjon:
      required:
        - liste
      allOf:
        - $ref: '#/components/schemas/InntektEndringAarsak'
      properties:
        liste:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
    Permittering:
      required:
        - liste
      allOf:
        - $ref: '#/components/schemas/InntektEndringAarsak'
      properties:
        liste:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
    Feilregistrert:
      allOf:
        - $ref: '#/components/schemas/InntektEndringAarsak'

    InntektsmeldingDokument:
      type: object
      required:
        - arbeidsgiverperioder
        - refusjon
        - virksomhetNavn
        - identitetsnummer
        - behandlingsdager
        - orgnrUnderenhet
        - fulltNavn
        - egenmeldingsperioder
        - fraværsperioder
        - bestemmendeFraværsdag
        - tidspunkt
        - beregnetInntekt
        - årsakInnsending
      properties:
        orgnrUnderenhet:
          type: string
        identitetsnummer:
          type: string
        fulltNavn:
          type: string
        virksomhetNavn:
          type: string
        behandlingsdager:
          type: array
          items:
            type: string
            format: date
        egenmeldingsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
        bestemmendeFraværsdag:
          type: string
          format: date
        fraværsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
        arbeidsgiverperioder:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
        beregnetInntekt:
          type: number
        inntekt:
          $ref: '#/components/schemas/Inntekt'
        fullLønnIArbeidsgiverPerioden:
          $ref: '#/components/schemas/FullLonnIArbeidsgiverPerioden'
        refusjon:
          $ref: '#/components/schemas/Refusjon'
        naturalytelser:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Naturalytelse'
        tidspunkt:
          type: string
          format: date-time
          pattern: yyyy-MM-dd'T'HH:mm:ss.SSSxx
        årsakInnsending:
          $ref: '#/components/schemas/ÅrsakInnsending'
        innsenderNavn:
          type: string
        telefonnummer:
          type: string
        forespurtData:
          type: array
          items:
            type: string
    FullLonnIArbeidsgiverPerioden:
      type: object
      required:
        - utbetalerFullLønn
      properties:
        utbetalerFullLønn:
          type: boolean
        begrunnelse:
          $ref: '#/components/schemas/BegrunnelseIngenEllerRedusertUtbetalingKode'
        utbetalt:
          type: number
    Periode:
      type: object
      required:
        - fom
        - tom
      properties:
        fom:
          type: string
          format: date
        tom:
          type: string
          format: date
    ÅrsakInnsending:
      type: string
      enum:
        - Ny
        - Endring
    BegrunnelseIngenEllerRedusertUtbetalingKode:
      type: string
      enum:
        - LovligFravaer
        - FravaerUtenGyldigGrunn
        - ArbeidOpphoert
        - BeskjedGittForSent
        - ManglerOpptjening
        - IkkeLoenn
        - BetvilerArbeidsufoerhet
        - IkkeFravaer
        - StreikEllerLockout
        - Permittering
        - FiskerMedHyre
        - Saerregler
        - FerieEllerAvspasering
        - IkkeFullStillingsandel
        - TidligereVirksomhet
    NaturalytelseKode:
      type: string

      enum:
        - AKSJERGRUNNFONDSBEVISTILUNDERKURS
        - LOSJI
        - KOSTDOEGN
        - BESOEKSREISERHJEMMETANNET
        - KOSTBESPARELSEIHJEMMET
        - RENTEFORDELLAAN
        - BIL
        - KOSTDAGER
        - BOLIG
        - SKATTEPLIKTIGDELFORSIKRINGER
        - FRITRANSPORT
        - OPSJONER
        - TILSKUDDBARNEHAGEPLASS
        - ANNET
        - BEDRIFTSBARNEHAGEPLASS
        - YRKEBILTJENESTLIGBEHOVKILOMETER
        - YRKEBILTJENESTLIGBEHOVLISTEPRIS
        - INNBETALINGTILUTENLANDSKPENSJONSORDNING
        - ELEKTRONISKKOMMUNIKASJON
    Naturalytelse:
      required:
        - naturalytelse
        - dato
        - beløp
      properties:
        naturalytelse:
          $ref: '#/components/schemas/NaturalytelseKode'
        dato:
          type: string
          format: date
          description: "just a date"
        beløp:
          type: number
    Refusjon:
      required:
        - utbetalerHeleEllerDeler
      properties:
        utbetalerHeleEllerDeler:
          type: boolean
          nullable: false
        refusjonPrMnd:
            type: number
            nullable: false
        refusjonOpphører:
            type: string
            format: date
            nullable: true
        refusjonEndringer:
            type: array
            nullable: true
            items:
              $ref: '#/components/schemas/RefusjonEndring'
    RefusjonEndring:
      properties:
        beløp:
          type: number
        dato:
          type: string
          format: date