kafkaPool: nav-dev
azure:
  enabled: true
ingress: https://helsearbeidsgiver-im-kontroll.dev.nav.no
env:
- name: ENHETSREGISTERET_URL
  value: "https://data.brreg.no/enhetsregisteret/api/underenheter/"
