kafkaPool: nav-dev
azure:
  enabled: true
ingress: https://helsearbeidsgiver-im-brreg.intern.dev.nav.no
env:
- name: ENHETSREGISTERET_URL
  value: "http://localhost"
externalHosts:
  - helsearbeidsgiver-proxy.prod-fss-pub.nais.io
