kafkaPool: nav-dev
azure:
  enabled: true
ingress: https://helsearbeidsgiver-im-joark.dev.nav.no
env:
- name: PROXY_SCOPE
  value: "api://dev-fss.helsearbeidsgiver.helsearbeidsgiver-proxy/.default"
- name: DOKARKIV_URL
  value: "https://helsearbeidsgiver-proxy.dev-fss-pub.nais.io/dokarkiv"
