kafkaPool: nav-dev
azure:
  enabled: true
ingress: https://helsearbeidsgiver-im-joark.intern.dev.nav.no
env:
- name: PROXY_SCOPE
  value: "api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default"
- name: DOKARKIV_URL
  value: "https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost?forsoekFerdigstill=$ferdigstill"
externalHosts:
  - dokarkiv.dev-fss-pub.nais.io
