kafkaPool: nav-dev
azure:
  enabled: true
ingress: https://helsearbeidsgiver-im-joark.dev.nav.no
env:
- name: DOKARKIV_URL
  value: ""
- name: PROXY_SCOPE
  value: "api://dev-fss.helsearbeidsgiver.helsearbeidsgiver-proxy/.default"