kafkaPool: nav-dev
entraIdEnabled: true
env:
- name: DOKARKIV_SCOPE
  value: "api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default"
- name: DOKARKIV_URL
  value: "https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1"
externalHosts:
  - dokarkiv.dev-fss-pub.nais.io
