kafkaPool: nav-prod
azure:
  enabled: true
env:
- name: DOKARKIV_SCOPE
  value: "api://dev-fss.teamdokumenthandtering.dokarkiv/.default"
- name: DOKARKIV_URL
  value: "https://dokarkiv.prod-fss-pub.nais.io/dokarkiv/rest/journalpostapi/v1"
externalHosts:
  - dokarkiv.prod-fss-pub.nais.io
