kafkaPool: nav-prod
azure:
  enabled: true
env:
  - name: PROXY_SCOPE
    value: "api://prod-fss.helsearbeidsgiver.helsearbeidsgiver-proxy/.default"
  - name: SPINN_URL
    value: "https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/syfoinntektsmelding"
  - name: KAFKA_EXTRA_TOPIC
    value: helsearbeidsgiver.pri
externalHosts:
  - helsearbeidsgiver-proxy.prod-fss-pub.nais.io
