version: '3.4'

networks:
  kafka-net:
    driver: bridge

services:
# todo: postgres
  im_zookeeper:
    image: 'bitnami/zookeeper:3.6'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  im_kafka:
    image: 'bitnami/kafka:3.3.1'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=im_zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - im_zookeeper

#  mock-oauth2-server:
#    image: ghcr.io/navikt/mock-oauth2-server:0.5.7
#    ports:
#      - '8080:8080'
#    hostname: host.docker.internal

  redis:
    image: redis:7
    ports:
      - 6379:6379

volumes:
  data:
