### Hent fra Spleis / Helsebro
GET http://0.0.0.0:8080/api/v1/kvittering?uuid=77c9e7ed-efcc-45e5-9177-4db2d4e466c1
Content-Type: application/json

> {%
client.test("Response OK", () => {
    client.assert(response.status === 403, "Response not OK: " + response.status)
})
%}