### Preutfyll
POST https://helsearbeidsgiver-im-api.dev.nav.no/api/v1/inntektsmelding
Content-Type: application/json

{
  "orgnrUnderenhet": "123456785",
  "identitetsnummer": "10107400090",
  "behandlingsdager": [
    "2022-10-21"
  ],
  "egenmeldingsperioder": [
    {
      "fom": "2022-10-21",
      "tom": "2022-10-23"
    }
  ],
  "beregnetInntekt": 32100.0,
  "beregnetInntektEndringÅrsak": "Tariffendring",
  "fullLønnIArbeidsgiverPerioden": {
    "utbetalerFullLønn": true,
    "begrunnelse": "ArbeidOpphoert"
  },
  "refusjon": {
    "refusjonPrMnd": 2500.0,
    "refusjonOpphører": "2022-10-21"
  },
  "naturalytelser": [
    {
      "naturalytelse": "Bil",
      "dato": "2022-10-21",
      "beløp": 300.0
    }
  ],
  "bekreftOpplysninger": true
}

> {%
client.test("Response OK", () => {
    client.assert(response.status === 200, "Response not OK: " + response.status)
})
%}