kafkaPool: nav-dev
replicasMax: 5
entraIdEnabled: true
apps:
  - name: sykepengesoknad-backend
    namespace: flex
env:
  - name: SOEKNAD_BASE_URL
    value: http://sykepengesoknad-backend.flex
  - name: SOEKNAD_SCOPE
    value: api://dev-gcp.flex.sykepengesoknad-backend/.default
