kafkaPool: nav-dev
replicasMax: 5
entraIdEnabled: true
env:
- name: PDL_URL
  value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
- name: PDL_SCOPE
  value: "api://dev-fss.pdl.pdl-api/.default"
externalHosts:
  - pdl-api.dev-fss-pub.nais.io
