kafkaPool: nav-prod
entraIdEnabled: true
env:
- name: PDL_URL
  value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
- name: PDL_SCOPE
  value: "api://prod-fss.pdl.pdl-api/.default"
externalHosts:
  - pdl-api.prod-fss-pub.nais.io
