kafkaPool: nav-dev
azure:
  enabled: true
replicasMin: 2
replicasMax: 2
apps:
  - name: arbeidsgiver-altinn-tilganger
    namespace: fager
env:
  - name: ALTINN_SERVICE_CODE
    value: 4936
  - name: ALTINN_TILGANGER_SCOPE
    value: api://dev-gcp.fager.arbeidsgiver-altinn-tilganger/.default
  - name: ALTINN_TILGANGER_BASE_URL
    value: http://arbeidsgiver-altinn-tilganger.fager
