kafkaPool: nav-dev
azure:
  enabled: true
replicasMin: 2
replicasMax: 2
ingress: https://helsearbeidsgiver-im-altinn.intern.dev.nav.no
envFrom:
  - type: secret
    name: altinn-api-gw-keys
env:
  - name: ALTINN_URL
    value: https://api-gw-q1.oera.no/ekstern/altinn/api/serviceowner
  - name: ALTINN_SERVICE_CODE
    value: 4936
externalHosts:
  - api-gw-q1.oera.no
