kafkaPool: nav-prod
azure:
  enabled: true
envFrom:
  - type: secret
    name: altinn-api-gw-keys-prod
env:
  - name: ALTINN_URL
    value: https://altinn.no/api/serviceowner
  - name: ALTINN_SERVICE_CODE
    value: 4936
  - name: ALTINN_SCOPE
    value: altinn:serviceowner/reportees
externalHosts:
  - altinn.no
maskinporten:
  consumes:
    - "altinn:serviceowner/reportees"
