kafkaPool: nav-prod
replicasMax: 5
entraIdEnabled: true
requestMem: 2048Mi
limitMem: 4096Mi

apps:
  - name: arbeidsgiver-altinn-tilganger
    namespace: fager
env:
  - name: ALTINN_TILGANGER_SCOPE
    value: api://prod-gcp.fager.arbeidsgiver-altinn-tilganger/.default
  - name: ALTINN_TILGANGER_BASE_URL
    value: http://arbeidsgiver-altinn-tilganger.fager
