package no.nav.hag.simba.utils.felles

import kotlinx.serialization.Serializable

@Serializable
enum class BehovType {
    // Hente data
    HENT_ANSETTELSESPERIODER,
    ARBEIDSGIVERE,
    HENT_INNTEKT,
    HENT_LAGRET_IM,
    HENT_PERSONER,
    HENT_SELVBESTEMT_IM,
    HENT_TRENGER_IM, // TODO: SPLEIS_FORESPOERSEL eller SPLEIS_FORESPOERSEL_DETALJER??
    HENT_VIRKSOMHET_NAVN,
    TILGANGSKONTROLL,
    HENT_FORESPOERSLER_FOR_VEDTAKSPERIODE_ID_LISTE,

    // Synkrone endringer
    LAGRE_IM_SKJEMA,
    LAGRE_IM,
    LAGRE_SELVBESTEMT_IM,
    OPPRETT_SELVBESTEMT_SAK,
}

@Serializable
enum class EventName {
    // Sendes fra API-appen for å sette i gang hendelsesbaserte flyter
    TILGANG_FORESPOERSEL_REQUESTED,
    TILGANG_ORG_REQUESTED,
    TRENGER_REQUESTED,
    FORESPOERSLER_REQUESTED,
    INNTEKT_REQUESTED,
    INNTEKT_SELVBESTEMT_REQUESTED,
    KVITTERING_REQUESTED,
    SELVBESTEMT_IM_REQUESTED,
    AKTIVE_ORGNR_REQUESTED,

    // Brukes internt i servicene for å utføre stegvise flyter
    SERVICE_HENT_TILGANG_FORESPOERSEL,
    SERVICE_HENT_TILGANG_ORG,
    SERVICE_HENT_AKTIVE_ORGNR,
    SERVICE_HENT_INNTEKT,
    SERVICE_HENT_INNTEKT_SELVBESTEMT,
    SERVICE_HENT_FORESPOERSEL,
    SERVICE_HENT_FORESPOERSEL_LISTE,
    SERVICE_HENT_DATA_TIL_SAK_OG_OPPGAVE,
    SERVICE_FORESPURT_IM_HENT,
    SERVICE_FORESPURT_IM_LAGRE_SKJEMA,
    SERVICE_SELVBESTEMT_IM_HENT,
    SERVICE_SELVBESTEMT_IM_LAGRE,
    SERVICE_EKSTERN_IM_VALIDER,
    SERVICE_EKSTERN_IM_LAGRE_SKJEMA,
    SERVICE_BERIK_INNTEKTSMELDING,

    // Resterende er hendelser i konvensjonell forstand
    API_INNSENDING_STARTET,
    API_INNSENDING_VALIDERT,
    INSENDING_STARTED,

    SELVBESTEMT_IM_MOTTATT,
    SELVBESTEMT_IM_LAGRET,

    EKSTERN_INNTEKTSMELDING_MOTTATT,
    EKSTERN_INNTEKTSMELDING_LAGRET,

    INNTEKTSMELDING_SKJEMA_LAGRET,
    INNTEKTSMELDING_MOTTATT,
    INNTEKTSMELDING_JOURNALFOERT,
    INNTEKTSMELDING_JOURNALPOST_ID_LAGRET,
    INNTEKTSMELDING_DISTRIBUERT,

    FORESPOERSEL_MOTTATT,
    FORESPOERSEL_BESVART,
    FORESPOERSEL_FORKASTET,
    FORESPOERSEL_KASTET_TIL_INFOTRYGD,

    SAK_OG_OPPGAVE_OPPRETT_REQUESTED,
    SAK_OG_OPPGAVE_OPPRETTET,
    SAK_OG_OPPGAVE_FERDIGSTILT,
    SAK_OG_OPPGAVE_UTGAATT,
}
