kafkaPool: nav-dev
entraIdEnabled: true
env:
- name: AAREG_URL
  value: "https://aareg-services.dev-fss-pub.nais.io"
- name: AAREG_SCOPE
  value: "api://dev-fss.arbeidsforhold.aareg-services-nais/.default"
externalHosts:
  - aareg-services.dev-fss-pub.nais.io
