kafkaPool: nav-dev
azure:
  enabled: true
ingress: https://helsearbeidsgiver-im-aareg.intern.dev.nav.no
env:
- name: AAREG_URL
  value: "https://helsearbeidsgiver-proxy.dev-fss-pub.nais.io/aareg-arbeidsforhold"
- name: PROXY_SCOPE
  value: "api://dev-fss.helsearbeidsgiver.helsearbeidsgiver-proxy/.default"
externalHosts:
  - helsearbeidsgiver-proxy.dev-fss-pub.nais.io
