kafkaPool: nav-dev
azure:
  enabled: true
ingress: https://helsearbeidsgiver-im-aareg.intern.dev.nav.no
env:
- name: AAREG_URL
  value: "https://aareg-services.dev-fss-pub.nais.io/api/v1/arbeidstaker/arbeidsforhold?sporingsinformasjon=false&historikk=false"
- name: AAREG_SCOPE
  value: "api://dev-fss.arbeidsforhold.aareg-services-nais/.default"
externalHosts:
  - aareg-services.dev-fss-pub.nais.io
