kafkaPool: nav-prod
entraIdEnabled: true
env:
- name: AAREG_URL
  value: "https://aareg-services.prod-fss-pub.nais.io"
- name: AAREG_SCOPE
  value: "api://prod-fss.arbeidsforhold.aareg-services-nais/.default"
externalHosts:
  - aareg-services.prod-fss-pub.nais.io
