kafkaPool: nav-prod
azure:
  enabled: true
env:
- name: AAREG_URL
  value: "https://aareg-services.prod-fss-pub.nais.io/api/v1/arbeidstaker/arbeidsforhold?sporingsinformasjon=false&historikk=false"
- name: AAREG_SCOPE
  value: "api://prod-fss.arbeidsforhold.aareg-services-nais/.default"
externalHosts:
  - aareg-services.prod-fss-pub.nais.io
