kafkaPool: nav-prod
azure:
  enabled: true
env:
- name: AAREG_URL
  value: "https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/aareg-arbeidsforhold"
- name: PROXY_SCOPE
  value: "api://prod-fss.helsearbeidsgiver.helsearbeidsgiver-proxy/.default"
externalHosts:
  - helsearbeidsgiver-proxy.prod-fss-pub.nais.io
