kafkaPool: nav-dev
entraIdEnabled: true
env:
- name: INNTEKT_URL
  value: "https://team-inntekt-proxy.dev-fss-pub.nais.io/proxy/inntektskomponenten-q2/rs"
- name: INNTEKT_SCOPE
  value: "api://dev-fss.team-inntekt.inntektskomponenten/.default"
externalHosts:
  - team-inntekt-proxy.dev-fss-pub.nais.io
