kafkaPool: nav-dev
entraIdEnabled: true
env:
- name: INNTEKT_URL
  value: "https://ikomp-q2.dev-fss-pub.nais.io/inntektskomponenten-q2/rs"
- name: INNTEKT_SCOPE
  value: "api://dev-fss.team-inntekt.ikomp-q2/.default"
externalHosts:
  - team-inntekt-proxy.dev-fss-pub.nais.io
