kafkaPool: nav-dev
entraIdEnabled: true
env:
- name: INNTEKT_URL
  value: "https://ikomp-q1.dev-fss-pub.nais.io/inntektskomponenten/rs"
- name: INNTEKT_SCOPE
  value: "api://dev-fss.team-inntekt.ikomp-q1/.default"
externalHosts:
  - ikomp-q1.dev-fss-pub.nais.io
