kafkaPool: nav-dev
replicasMax: 5
entraIdEnabled: true
env:
- name: INNTEKT_URL
  value: "https://ikomp-q2.dev-fss-pub.nais.io/rs"
- name: INNTEKT_SCOPE
  value: "api://dev-fss.team-inntekt.ikomp-q2/.default"
externalHosts:
  - ikomp-q2.dev-fss-pub.nais.io
