kafkaPool: nav-prod
entraIdEnabled: true
env:
- name: INNTEKT_URL
  value: "https://ikomp.prod-fss-pub.nais.io/rs"
- name: INNTEKT_SCOPE
  value: "api://prod-fss.team-inntekt.ikomp/.default"
externalHosts:
  - ikomp.prod-fss-pub.nais.io
