kafkaPool: nav-prod
azure:
  enabled: true
env:
- name: INNTEKT_URL
  value: "https://team-inntekt-proxy.prod-fss-pub.nais.io/proxy/inntektskomponenten/rs"
- name: INNTEKT_SCOPE
  value: "api://prod-fss.team-inntekt.inntektskomponenten/.default"
externalHosts:
  - team-inntekt-proxy.prod-fss-pub.nais.io
