kafkaPool: nav-dev
azure:
  enabled: true
ingress: https://helsearbeidsgiver-im-feil-behandler.intern.dev.nav.no
database: register
envFrom:
  - type: secret
    name: google-sql-im-feil-behandler
env:
