kafkaPool: nav-dev
azure:
  enabled: true
database:
  - name: inntektsmelding
    users: [ simba_datastream_bruker ]
logical_decoding: true
dbTier: db-custom-1-3840
envFrom:
  - type: secret
    name: google-sql-im-db
