kafkaPool: nav-prod
azure:
  enabled: true
database:
  - name: inntektsmelding
    users: [ simba_datastream_bruker ]
logical_decoding: true
dbTier: db-f1-micro
envFrom:
  - type: secret
    name: google-sql-im-db
