kafkaPool: nav-prod
replicasMax: 5
database:
  name: inntektsmelding
  tier: db-custom-1-3840
  logicalDecoding: true
  user: simba_datastream_bruker
envFrom:
  - type: secret
    name: google-sql-im-db
