kafkaPool: nav-dev
azure:
  enabled: true
env:
  - name: PROXY_SCOPE
    value: "api://dev-fss.helsearbeidsgiver.syfoinntektsmelding/.default"
  - name: SPINN_API_URL
    value: "https://syfoinntektsmelding.dev-fss-pub.nais.io/api/v1/inntektsmelding"
  - name: REDIS_URL
    value: redis://helsearbeidsgiver-redis.helsearbeidsgiver.svc.cluster.local:6379/0
apps:
  - name: helsearbeidsgiver-redis
externalHosts:
  - helsearbeidsgiver-proxy.dev-fss-pub.nais.io
