kafkaPool: nav-prod
azure:
  enabled: true
env:
  - name: SPINN_SCOPE
    value: "api://prod-gcp.helsearbeidsgiver.spinosaurus/.default"
  - name: SPINN_API_URL
    value: "http://spinosaurus/api/v1/inntektsmelding"
apps:
  - name: spinosaurus
