kafkaPool: nav-prod
azure:
  enabled: true
env:
  - name: SPINN_SCOPE
    value: "api://prod-fss.helsearbeidsgiver.syfoinntektsmelding/.default"
  - name: SPINN_API_URL
    value: "https://syfoinntektsmelding.prod-fss-pub.nais.io/api/v1/inntektsmelding"
  - name: REDIS_URL
    value: redis://helsearbeidsgiver-redis.helsearbeidsgiver.svc.cluster.local:6379/0
apps:
  - name: helsearbeidsgiver-redis
externalHosts:
  - helsearbeidsgiver-proxy.prod-fss-pub.nais.io
