name: Build

on:
  push:
    branches:
      - main
      - preprod/**
      - dev/**

jobs:
  diff-matrix:
    uses: ./.github/workflows/reuse-diff-matrix.yml
    with:
      env: dev

  sjekk-output:
    needs: diff-matrix
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.diff-matrix.outputs.is-build-matrix-empty }}
          echo ${{ needs.diff-matrix.outputs.is-build-matrix-empty == 'false' }}

  build:
    needs: diff-matrix
    if: needs.diff-matrix.outputs.is-build-matrix-empty == 'false'
    uses: ./.github/workflows/reuse-build.yml
    with:
      build-matrix: ${{ needs.diff-matrix.outputs.build-matrix }}

  deploy:
    needs: [diff-matrix, build]
    uses: ./.github/workflows/reuse-deploy.yml
    with:
      env: dev
      deploy-matrix: ${{ needs.diff-matrix.outputs.deploy-matrix }}
