name: Build

on:
  push:
    branches:
      - main
      - preprod/**
      - dev/**

env:
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  diff-matrix:
    uses: ./.github/workflows/reuse-diff-matrix.yml
    with:
      env: dev

  build:
    needs: diff-matrix
    uses: ./.github/workflows/reuse-build.yml
    with:
      build-matrix: ${{ needs.diff-matrix.outputs.build-matrix }}

  deploy:
    needs: [diff-matrix, build]
    uses: ./.github/workflows/reuse-deploy.yml
    with:
      env: dev
      deploy-matrix: ${{ needs.diff-matrix.outputs.deploy-matrix }}
