name: Monitor dependencies with Dependabot
on:
  push:
    branches:
      - main
    paths:
      - "**.gradle.kts"
      - "gradle.properties"
  workflow_dispatch:
jobs:
  dependabot:
    name: Monitor dependencies with Dependabot
    runs-on: ubuntu-20.04
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v3 # ratchet:actions/checkout@v3
      - name: Run snapshot action
        env:
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          sub-module-mode: COMBINED
          gradle-build-module: |-
            :aareg
            :akkumulator
            :altinn
            :api
            :brreg
            :db
            :distribusjon
            :dokument
            :felles
            :forespoersel-mottatt
            :helsebro
            :innsending
            :inntekt
            :joark
            :notifikasjon
            :pdl
            :preutfylt
          fail-on-error: false
