name: Monitor dependencies with Dependabot
on:
  push:
    branches:
      - main
    paths:
      - "**.gradle.kts"
      - "gradle.properties"
  workflow_dispatch:
jobs:
  dependabot:
    name: Monitor dependencies with Dependabot
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v3 # ratchet:actions/checkout@v3
      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@{latest}
        with:
          sub-module-mode: COMBINED
          fail-on-error: false
          include-build-environment: true
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}