name: Ktlint

on: pull_request

jobs:
  Ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: '{ "create_artifact": false, "enabled": true, "debug": false }'
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: "Install ktlint"
        uses: nbadal/action-ktlint-setup@v1
        with:
          ktlint_version: '0.42.1'
      - run: ktlint
        shell: bash