name: Test

on: pull_request

jobs:
  Test:
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v5

      - name: Test
        run: ./gradlew test --tests --parallel --build-cache '*Test' jacocoTestReport -Dorg.gradle.jvmargs=-Xmx32g -x :integrasjonstest:test
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
