name: Produksjon

on:
  release:
    types: [released]

jobs:
  diff-matrix:
    uses: ./.github/workflows/reuse-diff-matrix.yml
    with:
      env: prod

  build:
    needs: diff-matrix
    uses: ./.github/workflows/reuse-build.yml
    with:
      build-matrix: ${{ needs.diff-matrix.outputs.build-matrix }}
    permissions:
      id-token: write

  deploy:
    needs: [diff-matrix, build]
    uses: ./.github/workflows/reuse-deploy.yml
    with:
      deploy-matrix: ${{ needs.diff-matrix.outputs.deploy-matrix }}
    permissions:
      id-token: write
