name: Test

on: pull_request

jobs:
  Test:
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4

      - name: Test
        run: |
          ./gradlew :integrasjonstest:test -Porg.gradle.parallel=false --tests '*Test'
          ./gradlew test --parallel --build-cache --tests '*Test' -Dorg.gradle.jvmargs=-Xmx32g -x :integrasjonstest:test
          ./gradlew jacocoTestReport -Dorg.gradle.jvmargs=-Xmx32g
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
