kafkaPool: nav-prod
idportenEnabled: true
sidecarEnabled: true
tokenxEnabled: true
azure:
  enabled: true
ingress: https://helsearbeidsgiver-im-api.intern.nav.no
env:
  - name: REDIS_URL
    value: redis://helsearbeidsgiver-redis.helsearbeidsgiver.svc.cluster.local:6379/0
apps:
  - name: helsearbeidsgiver-redis
inboundApps:
  - name: spinntektsmelding-frontend
